name: "Delete old folders from S3"
on:
  push:
  workflow_dispatch:
  
permissions:
  id-token: write


jobs:
  remove:
    runs-on: ubuntu-latest

    steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
       aws-access-key-id: AKIA6BIPVMUD24P2CY6F
       aws-secret-access-key: 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
       aws-region: us-east-1

    - name: List S3 bucket folders
      run: |
            folders=$(aws s3 ls s3://beni-bucket/testFolder/ --recursive --human-readable | sort -r)
            
            #echo $folders

            for folder in $folders; do
              last_modified=$(aws s3 ls s3://beni-bucket/testFolder/)
              timestamp=$(echo "$folder" | grep -oE '[0-9]{2}:[0-9]{2}:[0-9]{2}') 
              
              echo "$(date -d "${timestamp}" +%s) $folder"
              
              #echo $folder
            done










