name: "Delete old folders from S3"
on:
  push:
  workflow_dispatch:
  
permissions:
  id-token: write


jobs:
  remove:
    runs-on: ubuntu-latest

    steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
       aws-access-key-id: AKIARWBN6WILAX7UHBP6
       aws-secret-access-key: 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
       aws-region: us-east-1

    - name: List S3 bucket folders
      run: |
            aws s3 ls s3://awsbucketbeni/testFolder/ | while read -r line;
             do
              createDate=`echo $line|awk {'print $1" "$2'}`
              createDate=`date -d"$createDate" +%s`
              olderThan=`date --date "30 min ago" +%s`
              if [[ $createDate -lt $olderThan ]] 
                then 
                  fileName=`echo $line|awk {'print $4'}` 
                  
                  if [[ $fileName != "" ]]
                  then
                    echo $fileName
                  fi
              fi
              
              done;
