name: "Delete old folders from S3"
on:
  push:
  workflow_dispatch:
  
permissions:
  id-token: write


jobs:
  remove:
    runs-on: ubuntu-latest

    steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
       aws-access-key-id: AKIA3JFGV77ZKCMSAQAA
       aws-secret-access-key: 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
       aws-region: us-east-1

    - name: List S3 bucket folders
      run: |
            folders=$(aws s3 ls s3://beni-bucket/testFolder/)
            
            echo $folders

            for folder in $folders; do
              echo $folder
            done
