name: "Delete old folders from S3"
on:
  push:
  workflow_dispatch:
  
permissions:
  id-token: write


jobs:
  remove:
    runs-on: ubuntu-latest

    steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
       aws-access-key-id: AKIARQARJQ6T3H3PV3EO
       aws-secret-access-key: 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
       aws-region: us-east-1

    - name: List S3 bucket folders
      run: |
            now=$(date +%s)
            cutOff=$(date -d '-30 minutes' +%s)
            echo $cutOff
            folders=$(aws s3 ls s3://beni-bucket1/testFolder/ --recursive | sort | awk '{print $2}')
            
            echo $folders 
            arr=()
            newArr=()

            for folder in $folders; do
              arr+=("$folder")
            done
            

            for element in "${arr[@]}"; do
                if [ "$element" = '12:17:47' ]; then
                    newArr+=("$element")
                fi
            done

            echo "${newArr[@]}"

          

            













